spring.datasource.url=jdbc:mysql://localhost:3306/student-registration-form?useUnicode=true&useJDBCCompliantTimezone
Shift=true&useLegacyDatetimeCode=false&serverTimezone=UTC

spring.datasource.username=springstudent
spring.datasource.password=springstudent
server.error.whitelabel.enabled=false



spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html